---
title: "Exploratory data analysis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{EDA}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, include = FALSE}

library(dplyr)
library(ggplot2)
library(knitr)
library(skimr)
library(stringr)
library(tidyr)

library(brazildatamortality)

```


```{r check_variables, include=FALSE}

# TODO: Make figures by job_name
# TODO: Add the original age from the raw data.


# Join job names.
job_names_9  <- "/home/alber/Documents/github/brazildatamortality/data-raw/TABOCUP_cid9.DBF" %>% 
  ensurer::ensure_that(file.exists(.), err_desc = "File not found") %>% 
  foreign::read.dbf(as.is = TRUE) %>% 
  tibble::as_tibble() %>% 
  dplyr::rename(job = CODIGO,
                job_name = DESCRICAO)
job_names_10 <- "/home/alber/Documents/github/brazildatamortality/data-raw/TABOCUP_cid10.DBF" %>% 
  ensurer::ensure_that(file.exists(.), err_desc = "File not found") %>% 
  foreign::read.dbf() %>% 
  tibble::as_tibble(as.is = TRUE) %>% 
  dplyr::rename(job = CODIGO,
                job_name = DESCRICAO)
  
# Check that data before and after 1996 have the same variables and categories.
data_9  <- brazildatamortality::data_icd_9 %>% 
  dplyr::left_join(job_names_9, by = "job")
data_10 <- brazildatamortality::data_icd_10 %>% 
  dplyr::left_join(job_names_10, by = "job")

data_9 %>% 
  dplyr::select(job, job_name) %>% 
  dplyr::filter(is.na(job_name)) %>% 
  dplyr::group_by(job) %>% 
  dplyr::summarise(nas = n()) %>% 
  dplyr::arrange(dplyr::desc(nas)) %>% 
  readr::write_csv(file = "missing_job_codes_cid9.csv")
                   
data_10 %>% 
  dplyr::select(job, job_name) %>% 
  dplyr::filter(is.na(job_name)) %>% 
  dplyr::group_by(job) %>% 
  dplyr::summarise(nas = n()) %>% 
  dplyr::arrange(dplyr::desc(nas)) %>% 
  readr::write_csv(file = "missing_job_codes_cid10.csv")

colnames(data_10) %>% sort()
colnames(data_9)  %>% sort()

# OK
data_10 %>% sample_n(6) %>% pull(birth_date) %>% unique() %>% sort()
data_9  %>% sample_n(6) %>% pull(birth_date) %>% unique() %>% sort()

# NOTE: They don't math too much because data before 1996 is deficient. 
data_10 %>% pull(cause) %>% unique() %>% sort()
data_9  %>% pull(cause) %>% unique() %>% sort()

# NOTE: 6 versus 7 digit codes. 
data_10 %>% sample_n(6) %>% pull(residence_city) %>% unique() %>% sort()
data_9  %>% sample_n(6) %>% pull(residence_city) %>% unique() %>% sort()

# NOTE: 6 versus 7 digit codes. 
data_10 %>% sample_n(6) %>% pull(death_city) %>% unique() %>% sort()
data_9  %>% sample_n(6) %>% pull(death_city) %>% unique() %>% sort()

# OK
data_10 %>% sample_n(6) %>% pull(death_date) %>% unique() %>% sort()
data_9  %>% sample_n(6) %>% pull(death_date) %>% unique() %>% sort()

# DONE: Recode jobs.
data_10 %>% sample_n(6) %>% pull(job) %>% unique() %>% sort()
data_9  %>% sample_n(6) %>% pull(job) %>% unique() %>% sort()

# OK 
data_10 %>% sample_n(6) %>% pull(locus) %>% unique() %>% sort()
data_9  %>% sample_n(6) %>% pull(locus) %>% unique() %>% sort()

# OK
data_10 %>% pull(marital) %>% unique() %>% sort()
data_9  %>% pull(marital) %>% unique() %>% sort()

# OK
data_10 %>% pull(sex) %>% unique() %>% sort()
data_9  %>% pull(sex) %>% unique() %>% sort()

# OK
data_10 %>% pull(education) %>% unique() %>% sort()
data_9  %>% pull(education) %>% unique() %>% sort()

```



```{r merge_both_data, include=FALSE}

data_10 <- data_10 %>% 
    dplyr::select(birth_date, cause, death_city, death_date, education, 
                  job, locus, marital, residence_city, sex, color_race, 
                  literacy) %>% 
  dplyr::mutate(education = if_else(education == "Barchelor incomplete",
                                    "Barchelor", education))
data_9  <- data_9  %>% 
    dplyr::select(birth_date, cause, death_city, death_date, education, 
                  job, locus, marital, residence_city, sex) %>% 
    dplyr::mutate(color_race = NA,
                  literacy = NA)

data_tb <- data_9 %>%
  dplyr::bind_rows(data_10) %>%
  dplyr::mutate(death_year = lubridate::year(death_date),
                computed_age = difftime(death_date, birth_date, 
                                        units = "days"),
                death_month = as.integer(lubridate::month(death_date))) %>%
  tidyr::drop_na(cause, death_date)

outlier_data <- data_tb %>%
  dplyr::filter(death_date > as.Date("2011-01-10"),
                death_date < as.Date("2011-01-13"))

regular_data <- data_tb %>%
  dplyr::filter(death_date < as.Date("2011-01-11") | 
                death_date > as.Date("2011-01-12"))

```



## Abstract.

## Introduction.

## Materials and methods.

## Results.

```{r eda, echo=FALSE, fig.width = 7, fig.height = 5}

#library(GGally)

# data_tb %>%
#   dplyr::filter(death_year > 2005) %>%
#   dplyr::mutate(death_month = stringr::str_pad(death_month, pad = "0", width = 2)) %>%
#   dplyr::mutate(death_year = as.factor(death_year),
#                 death_month = as.factor(death_month)) %>%
#   dplyr::select(cause, education, locus, marital, 
#                 sex, death_year, death_month) %>%
#   GGally::ggpairs(ggplot2::aes(color = cause))

# data_tb %>%
#   dplyr::mutate(death_month = stringr::str_pad(death_month, pad = "0", 
#                                                width = 2)) %>%
#   dplyr::mutate(death_year = as.factor(death_year),
#                 death_month = as.factor(death_month)) %>%
#   dplyr::select(cause, education, locus, marital, 
#                 sex, death_year, death_month) %>%
#   tidyr::pivot_longer(education:death_month) %>%
#   ggplot2::ggplot(ggplot2::aes(y = value, fill = cause)) +
#   ggplot2::geom_bar(position = "fill") +
#   ggplot2::facet_wrap(vars(name), scales = "free") +
#   ggplot2::labs(x = NULL, y = NULL, fill = NULL)


```


```{r plot_cumsum, echo=FALSE, fig.width = 7, fig.height = 5}

regular_data %>%
  dplyr::group_by(death_year) %>%
  dplyr::summarize(fatalities = dplyr::n(), 
                   .groups = "drop") %>%
  dplyr::mutate(cumsum = cumsum(fatalities)) %>%
  dplyr::arrange(death_year) %>%
  ggplot2::ggplot(ggplot2::aes(x = death_year,
                               y = cumsum)) +
  ggplot2::geom_point() +
  ggplot2::geom_line() +
  ggplot2::xlab("Year") +
  ggplot2::ylab("Accumulated number of fatalities") +
  ggplot2::ggtitle("Cumulative number of deaths by forces of nature")


```

```{r plot_causes_cumsum, echo=FALSE, fig.width = 7, fig.height = 5}

regular_data %>%
  dplyr::group_by(cause, death_year) %>%
  dplyr::summarize(fatalities = dplyr::n()) %>%
  dplyr::mutate(cumsum = cumsum(fatalities)) %>%
  dplyr::ungroup() %>%
  dplyr::arrange(cause, death_year) %>%
  ggplot2::ggplot(ggplot2::aes(x = death_year,
                               y = cumsum,
                               color = cause,
                               group = cause)) +
  ggplot2::geom_point() +
  ggplot2::geom_line() +
  ggplot2::xlab("Year") +
  ggplot2::ylab("Cumulative number of fatalities") +
  ggplot2::ggtitle("Cumulative sum of deaths by cause")

```

```{r plot_total, echo=FALSE, fig.width = 7, fig.height = 5}

regular_data %>%
  dplyr::group_by(death_year) %>%
  dplyr::summarize(fatalities = dplyr::n(), 
                   .groups = "drop") %>%
  dplyr::mutate(moving_average = RcppRoll::roll_mean(fatalities, 
                                                     n = 5, 
                                                     align = "right", 
                                                     fill = NA,
                                                     na.rm = TRUE))  %>%
  dplyr::arrange(death_year) %>%
  ggplot2::ggplot(ggplot2::aes(x = death_year,
                               y = fatalities)) +
  ggplot2::geom_point() +
  ggplot2::geom_line(ggplot2::aes(x = death_year,
                                  y = moving_average),
                                  color = "blue") +
  ggplot2::xlab("Year") +
  ggplot2::ylab("Number of fatalities") +
  ggplot2::ggtitle("Total number of deaths by forces of nature")

```

```{r plot_causes_sex_cumsum, echo=FALSE, fig.width = 7, fig.height = 5}

regular_data %>%
  dplyr::filter(sex %in% c("Male", "Female")) %>%
  dplyr::group_by(sex, cause, death_year) %>%
  dplyr::arrange(sex, cause, death_year) %>%
  dplyr::summarize(fatalities = dplyr::n()) %>%
  dplyr::filter(cause %in% c("Cataclismyc", 
                             "Cataclismyc and Floods",
                             "Cold", 
                             "Lightning", 
                             "Landslide")) %>%
  dplyr::mutate(cumsum = cumsum(fatalities)) %>%
  dplyr::ungroup() %>%
  ggplot2::ggplot(ggplot2::aes(x = death_year,
                               y = cumsum,
                               color = cause,
                               group = cause)) +
  ggplot2::geom_point() +
  ggplot2::geom_line() +
  ggplot2::facet_wrap(~sex) +
  ggplot2::xlab("Year") +
  ggplot2::ylab("Cumulative number of fatalities by sex") +
  ggplot2::ggtitle("Cumulative sum of deaths by cause and sex")

regular_data %>%
  dplyr::filter(sex %in% c("Male", "Female")) %>%
  dplyr::group_by(sex, cause, death_year) %>%
  dplyr::arrange(sex, cause, death_year) %>%
  dplyr::summarize(fatalities = dplyr::n()) %>%
  dplyr::filter(!(cause %in% c("Cataclismyc", 
                             "Cataclismyc and Floods",
                             "Cold", 
                             "Lightning", 
                             "Landslide"))) %>%
  dplyr::mutate(cumsum = cumsum(fatalities)) %>%
  dplyr::ungroup() %>%
  ggplot2::ggplot(ggplot2::aes(x = death_year,
                               y = cumsum,
                               color = cause,
                               group = cause)) +
  ggplot2::geom_point() +
  ggplot2::geom_line() +
  ggplot2::facet_wrap(~sex) +
  ggplot2::xlab("Year") +
  ggplot2::ylab("Cumulative number of fatalities by sex") +
  ggplot2::ggtitle("Cumulative sum of deaths by cause and sex")

```

```{r plot_causes, echo=FALSE, fig.width = 7, fig.height = 5}

# High impact
data_tb %>%
  dplyr::group_by(cause, death_year) %>%
  dplyr::summarize(fatalities = dplyr::n(), 
                   .groups = "drop") %>%
  dplyr::arrange(cause, death_year) %>%
  dplyr::filter(cause %in% c("Cataclismyc",
                             "Cataclismyc and Floods", 
                             "Flood",
                             "Landslide",
                             "Lightning")) %>%             
  dplyr::filter(!is.na(cause), !is.na(death_year)) %>%
  ggplot2::ggplot(ggplot2::aes(x = death_year,
                               y = fatalities,
                               color = cause,
                               group = cause)) +
  ggplot2::geom_point() +
  ggplot2::geom_line() +
  ggplot2::xlab("Year") +
  ggplot2::ylab("Number of fatalities") +
  ggplot2::ggtitle("Death by cause") + 
  ggplot2::scale_color_brewer(palette = "Paired")

# Low impact
data_tb %>%
  dplyr::group_by(cause, death_year) %>%
  dplyr::summarize(fatalities = dplyr::n(), 
                   .groups = "drop") %>%
  dplyr::arrange(cause, death_year) %>%
  dplyr::filter(!(cause %in% c("Cataclismyc",
                             "Cataclismyc and Floods", 
                             "Flood",
                             "Landslide",
                             "Lightning"))) %>%             
  dplyr::filter(!is.na(cause), !is.na(death_year)) %>%
  ggplot2::ggplot(ggplot2::aes(x = death_year,
                               y = fatalities,
                               color = cause,
                               group = cause)) +
  ggplot2::geom_point() +
  ggplot2::geom_line() +
  ggplot2::xlab("Year") +
  ggplot2::ylab("Number of fatalities") +
  ggplot2::ggtitle("Death by cause") + 
  ggplot2::scale_color_brewer(palette = "Paired")

```



```{r plot_causes_esc_cumsum, echo=FALSE, fig.width = 7, fig.height = 5}

# WARNING: There is a GAP from 1995 to 2012
# The variables of CID9 and CID10 are not the same
regular_data %>%
  dplyr::mutate(education = as.factor(education),
                cause     = as.factor(cause)) %>%
  tidyr::drop_na(education) %>%
  dplyr::group_by(education, cause, death_year) %>%
  dplyr::arrange(education, cause, death_year) %>%
  dplyr::summarize(fatalities = dplyr::n()) %>%
  dplyr::mutate(cumsum = cumsum(fatalities)) %>%
  dplyr::ungroup() %>%
  ggplot2::ggplot(ggplot2::aes(x = death_year,
                               y = cumsum,
                               color = cause,
                               group = cause)) +
  ggplot2::geom_point() +
  ggplot2::geom_line() +
  #ggplot2::scale_color_brewer(palette = "Spectral") + 
  #ggplot2::scale_colour_viridis_d(option = "plasma") +
  ggplot2::facet_wrap(~education) +
  ggplot2::xlab("Year") +
  ggplot2::ylab("Cumulative number of fatalities by education") +
  ggplot2::ggtitle("Cumulative sum of deaths by cause and education")

```


```{r plot_by_cause, echo=FALSE, fig.width = 7, fig.height = 5}

regular_data %>%
  dplyr::group_by(death_year, cause) %>%
  dplyr::summarize(fatalities = log(dplyr::n()),
                   .groups = "drop") %>%
  # NOTE: Util function for adding the roll means as a new column.
  (function(x) {
    my_data <- x %>%
      dplyr::arrange(death_year, cause) %>%
      tidyr::pivot_wider(id_cols = death_year,
                         names_from = cause,
                         values_from = fatalities)
    my_roll <- RcppRoll::roll_mean(as.matrix(dplyr::select(my_data, 
                                                           -death_year)),
                                   n = 5,
                                   align = "right",
                                   fill = NA,
                                   na.rm = TRUE) %>%
      tibble::as_tibble() %>%
      magrittr::set_names(paste(names(.), "roll_mean", sep = "_")) %>%
      dplyr::mutate(death_year = my_data$death_year) %>%
      tidyr::pivot_longer(!death_year) %>%
      dplyr::rename(moving_average = value)
   my_data %>%
     tidyr::pivot_longer(!death_year,
                         names_to = "cause",
                         values_to = "fatalities") %>%
     dplyr::bind_cols(dplyr::select(my_roll, moving_average)) %>%
     return()
  }) %>%
  dplyr::arrange(death_year) %>%
  ggplot2::ggplot(ggplot2::aes(x = death_year,
                               y = fatalities)) +
  ggplot2::geom_point() +
  ggplot2::geom_line(ggplot2::aes(x = death_year,
                                  y = moving_average),
                                  color = "blue") +
  ggplot2::facet_wrap(~cause,
                      ncol = 3) +
  ggplot2::xlab("Year") +
  ggplot2::theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  ggplot2::ylab("Logarithm of the number of fatalities") +
  ggplot2::ggtitle("Number of deaths by forces of nature by cause")

```

```{r cause_state, echo=FALSE, fig.width = 10, fig.height = 7}

state_tb <- brazildatamortality::state_sf %>% 
  sf::st_set_geometry(NULL) %>% 
  dplyr::mutate(code_state = as.character(code_state))


data_tb %>%
  dplyr::mutate(code_state = stringr::str_sub(death_city, 1, 2)) %>% 
  dplyr::left_join(state_tb, by = "code_state") %>% 
  dplyr::group_by(death_year, cause, abbrev_state) %>%
  dplyr::summarize(fatalities = dplyr::n(),
                   .groups = "drop") %>%
  tidyr::drop_na() %>%
  ggplot2::ggplot(ggplot2::aes(x = death_year,
                               y = fatalities, 
                               color = cause, 
                               group = cause)) +
  ggplot2::geom_point() +
  ggplot2::geom_line() +
  ggplot2::facet_wrap(vars(abbrev_state)) +
  ggplot2::xlab("Year") +
  ggplot2::ylab("Number of fatalities") +
  ggplot2::ggtitle("Deaths by cause by state")

# cumsum
data_tb %>%
  dplyr::mutate(code_state = stringr::str_sub(death_city, 1, 2)) %>% 
  dplyr::left_join(state_tb, by = "code_state") %>% 
  dplyr::group_by(abbrev_state, cause, death_year) %>%
  dplyr::summarize(fatalities = dplyr::n()) %>%
  dplyr::mutate(cumsum = cumsum(fatalities)) %>%
  dplyr::ungroup() %>%
  dplyr::arrange(cause, death_year) %>%
  tidyr::drop_na() %>%
  dplyr::mutate_if(is.character, as.factor) %>%
  ggplot2::ggplot(ggplot2::aes(x = death_year,
                               y = cumsum, 
                               color = cause, 
                               )) +
  ggplot2::geom_point(ggplot2::aes(shape = cause)) +
  ggplot2::geom_line(ggplot2::aes(linetype = cause)) +
  ggplot2::facet_wrap(vars(abbrev_state)) +
  ggplot2::scale_y_log10() +
  ggplot2::xlab("Year") +
  ggplot2::ylab("Cumulative number of fatalities (log)") +
  ggplot2::ggtitle("Deaths by cause by state")


data_tb %>%
  dplyr::mutate(code_state = stringr::str_sub(death_city, 1, 2)) %>% 
  dplyr::left_join(state_tb, by = "code_state") %>% 
  dplyr::group_by(death_year, cause, name_region) %>%
  dplyr::summarize(fatalities = dplyr::n(), 
                   .groups = "drop") %>%
  tidyr::drop_na() %>%
  ggplot2::ggplot(ggplot2::aes(x = death_year,
                               y = fatalities, 
                               color = cause, 
                               group = cause)) +
  ggplot2::geom_point() +
  ggplot2::geom_line() +
  ggplot2::facet_wrap(vars(name_region)) +
  ggplot2::xlab("Year") +
  ggplot2::ylab("Number of fatalities") +
  ggplot2::ggtitle("Deaths by cause by region")

# cumsum
data_tb %>%
  dplyr::mutate(code_state = stringr::str_sub(death_city, 1, 2)) %>% 
  dplyr::left_join(state_tb, by = "code_state") %>% 
  dplyr::group_by(name_region, cause, death_year) %>%
  dplyr::summarize(fatalities = dplyr::n()) %>%
  dplyr::mutate(cumsum = cumsum(fatalities)) %>%
  dplyr::ungroup() %>%
  dplyr::arrange(cause, death_year) %>%
  tidyr::drop_na() %>%
  ggplot2::ggplot(ggplot2::aes(x = death_year,
                               y = cumsum, 
                               color = name_region)) +
  ggplot2::geom_point(ggplot2::aes(shape = name_region)) +
  ggplot2::geom_line(ggplot2::aes(linetype = name_region)) +
  ggplot2::facet_wrap(~cause) +
  ggplot2::scale_y_log10() +
  ggplot2::xlab("Year") +
  ggplot2::ylab("Cumulative number of fatalities (log)") +
  ggplot2::ggtitle("Deaths by cause by region")

```



```{r todo1, echo=FALSE, fig.width = 10, fig.height = 7}

# + data_10 cataclismyc, flood, and landslide
# + data_9 cataclismyc & floods, and Earth surface movement.

# NOTE: The increment of deaths by landslide in the Sudeste region.
data_tb %>%
  dplyr::filter(cause %in% c("Cataclismyc", "Flood", "Landslide", 
                             "Cataclismyc and Floods", 
                             "Earth surface movement and Eruption")) %>%
  dplyr::mutate(code_state = stringr::str_sub(death_city, 1, 2)) %>% 
  dplyr::left_join(state_tb, by = "code_state") %>% 
  dplyr::group_by(name_region, cause, death_year) %>%
  dplyr::summarize(fatalities = dplyr::n()) %>%
  dplyr::mutate(cumsum = cumsum(fatalities)) %>%
  dplyr::ungroup() %>%
  dplyr::arrange(cause, death_year) %>%
  tidyr::drop_na() %>%
  ggplot2::ggplot(ggplot2::aes(x = death_year,
                               y = cumsum, 
                               color = name_region)) +
  ggplot2::geom_point(ggplot2::aes(shape = name_region)) +
  ggplot2::geom_line(ggplot2::aes(linetype = name_region)) +
  ggplot2::facet_wrap(~cause) +
  ggplot2::scale_y_log10() +
  ggplot2::xlab("Year") +
  ggplot2::ylab("Cumulative number of fatalities (log)") +
  ggplot2::ggtitle("Deaths by cause by region")

data_tb %>%
  dplyr::mutate(code_state = stringr::str_sub(death_city, 1, 2)) %>% 
  dplyr::left_join(state_tb, by = "code_state") %>% 
  dplyr::filter(cause %in% c("Cataclismyc", "Flood", "Landslide", 
                             "Cataclismyc and Floods", 
                             "Earth surface movement and Eruption"),
                name_region == "Sudeste") %>% 
  dplyr::group_by(abbrev_state, cause, death_year) %>%
  dplyr::summarize(fatalities = dplyr::n()) %>%
  dplyr::mutate(cumsum = cumsum(fatalities)) %>%
  dplyr::ungroup() %>%
  dplyr::arrange(cause, death_year) %>%
  tidyr::drop_na() %>%
  dplyr::mutate_if(is.character, as.factor) %>%
  ggplot2::ggplot(ggplot2::aes(x = death_year,
                               y = cumsum, 
                               color = cause, 
                               )) +
  ggplot2::geom_point(ggplot2::aes(shape = cause)) +
  ggplot2::geom_line(ggplot2::aes(linetype = cause)) +
  ggplot2::facet_wrap(vars(abbrev_state)) +
  ggplot2::scale_y_log10() +
  ggplot2::xlab("Year") +
  ggplot2::ylab("Cumulative number of fatalities (log)") +
  ggplot2::ggtitle("Deaths by cause by state")

```



```{r todo3, echo=FALSE, fig.width = 10, fig.height = 7}

# TODO: Join by code_muni creates many NAs
# #+ maps by region? by state? which year?
# town_data <- data_tb %>%
#   dplyr::left_join(town_tb, 
#                    by = c("death_city" = "code_muni")) %>%
#   dplyr::group_by(death_city, cause) %>%
#   dplyr::summarize(fatalities = dplyr::n()) %>%
#   dplyr::ungroup() %>%
#   dplyr::mutate(cause = stringr::str_replace_all(cause, 
#                                                  pattern = " ",
#                                                  replacement = "_")) %>%
#   tidyr::pivot_wider(id_cols = death_city, 
#                      names_from = cause,
#                      values_from = fatalities)

# TODO: Join by code_muni creates many NAs
# my_region <- "Sudeste"
# town_sf %>%
#   sf::st_make_valid() %>% 
#   dplyr::select(code_muni) %>%
#   dplyr::mutate(code_muni = as.character(code_muni)) %>%
#   sf::st_centroid() %>% 
#   dplyr::left_join(town_tb, by = "code_muni") %>%
#   dplyr::left_join(town_data, by = c("code_muni" = "death_city")) %>%
#   dplyr::filter(name_region == my_region) %>%
#   ggplot2::ggplot() +
#   ggplot2::geom_sf(data = dplyr::filter(town_sf, 
#                                         name_region == my_region)) +
#   ggplot2::geom_sf(ggplot2::aes(color = Lightning, 
#                                 size  = Lightning)) 

# State
state_data <- data_tb %>%
  dplyr::mutate(code_state = stringr::str_sub(death_city, 1, 2)) %>% 
  dplyr::left_join(state_tb, by = "code_state") %>% 
  dplyr::group_by(abbrev_state, cause) %>%
  dplyr::summarize(fatalities = dplyr::n()) %>%
  dplyr::ungroup()

state_hex <- brazildatamortality::state_hex
 
plot_sf <- merge(state_hex, state_data,
                 by = "abbrev_state",
                 all.x = TRUE)
plot_sf %>%
  ggplot2::ggplot() +
  ggplot2::geom_sf(data = state_hex) +
  ggplot2::geom_sf_label(ggplot2::aes(label = abbrev_state))
plot_sf %>%
  ggplot2::ggplot() +
  ggplot2::geom_sf(data = state_hex) +
  ggplot2::geom_sf(ggplot2::aes(fill = log10(fatalities)), colour = NA) +
  ggplot2::scale_fill_viridis_c(option = 'plasma') +
  ggplot2::facet_wrap(~cause)

```


```{r map_by_year, echo=FALSE}

hydrogeo_causes <- c("Cataclismyc", 
                     "Cataclismyc and Floods",
                     "Earth surface and Eruption",
                     "Flood",
                     "Landslide",
                     "Earthquake")
for (y in c(seq(from = 1980, to = 2015, by = 5), 2019)) {
  state_year_data <- data_tb %>%
    dplyr::mutate(death_year = lubridate::year(death_date)) %>% 
    dplyr::filter(cause %in% hydrogeo_causes,
                  death_year <= y) %>% 
    dplyr::mutate(code_state = stringr::str_sub(death_city, 1, 2)) %>% 
    dplyr::left_join(state_tb, by = "code_state") %>% 
    dplyr::group_by(abbrev_state) %>%
    dplyr::summarise(fatalities = dplyr::n()) %>% 
    dplyr::ungroup()
    plot_sf <- merge(state_hex, state_year_data,
                   by = "abbrev_state",
                   all.x = TRUE)
  my_plot <- plot_sf %>% 
    ggplot2::ggplot() +
    ggplot2::geom_sf(data = state_hex) +
    ggplot2::geom_sf(ggplot2::aes(fill = log10(fatalities)), colour = NA) +
    viridis::scale_fill_viridis(limits = c(0, 4), oob = scales::squish) +
    #ggplot2::geom_sf_label(ggplot2::aes(label = fatalities)) + 
    ggplot2::ggtitle(sprintf("Hydro-geological deaths until %s", y))
  print(my_plot)
} 

```


```{r todo2, echo=FALSE, fig.width = 10, fig.height = 7}

# + Add figure of low impact death causes by season (x = month, 
# y = number of fatalities, color = cause).

data_tb %>%
  dplyr::filter(cause %in% c("Cataclismyc", "Flood", "Landslide", 
                             "Cataclismyc and Floods", 
                             "Earth surface movement and Eruption")) %>%
  dplyr::select(cause, death_month) %>%
  tidyr::drop_na() %>%
  dplyr::mutate_all(as.factor) %>%
  ggplot2::ggplot() +
  ggplot2::geom_bar(ggplot2::aes(x = death_month,
                               fill = cause)) +
  ggplot2::xlab("Month") +
  ggplot2::ylab("Number of fatalities") +
  ggplot2::ggtitle("Deaths by cause by month")

data_tb %>%
  dplyr::filter(cause %in% c("Cataclismyc", "Flood", "Landslide", 
                             "Cataclismyc and Floods", 
                             "Earth surface movement and Eruption")) %>%
  dplyr::mutate(code_state = stringr::str_sub(death_city, 1, 2)) %>% 
  dplyr::left_join(state_tb, by = "code_state") %>% 
  dplyr::select(name_region, cause, death_month) %>%
  tidyr::drop_na() %>%
  dplyr::mutate_all(as.factor) %>%
  ggplot2::ggplot() +
  ggplot2::geom_bar(ggplot2::aes(x = death_month,
                               fill = cause)) +
  ggplot2::facet_wrap(~name_region) +
  ggplot2::xlab("Month") +
  ggplot2::ylab("Number of fatalities") +
  ggplot2::ggtitle("Deaths by cause by region and month")

```



## Conclusions.

## References.
